// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users/rpc/service.proto

package rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Request
type RegisterRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38998d4490fb2557, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// Response
type RegisterResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38998d4490fb2557, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RegisterResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "ms.users.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "ms.users.RegisterResponse")
}

func init() {
	proto.RegisterFile("users/rpc/service.proto", fileDescriptor_38998d4490fb2557)
}

var fileDescriptor_38998d4490fb2557 = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0xb1, 0xcb, 0xc2, 0x30,
	0x10, 0x47, 0x69, 0x4b, 0x3f, 0xfa, 0xdd, 0xa0, 0x12, 0x04, 0x6b, 0x27, 0xe9, 0xe4, 0x94, 0x82,
	0x2e, 0xae, 0xba, 0xe9, 0x18, 0x70, 0x71, 0xab, 0xed, 0x21, 0x41, 0xda, 0xc4, 0xbb, 0x54, 0xff,
	0x7d, 0x69, 0x6b, 0x15, 0xc4, 0xf1, 0xc7, 0x23, 0x2f, 0xef, 0x60, 0xd6, 0x30, 0x12, 0x67, 0x64,
	0x8b, 0x8c, 0x91, 0xee, 0xba, 0x40, 0x69, 0xc9, 0x38, 0x23, 0xa2, 0x8a, 0x65, 0xc7, 0xd2, 0x3d,
	0x8c, 0x15, 0x5e, 0x34, 0x3b, 0x24, 0x85, 0xb7, 0x06, 0xd9, 0x89, 0x04, 0xa2, 0x96, 0xd5, 0x79,
	0x85, 0xb1, 0xb7, 0xf0, 0x96, 0xff, 0xea, 0xbd, 0x5b, 0x66, 0x73, 0xe6, 0x87, 0xa1, 0x32, 0xf6,
	0x7b, 0x36, 0xec, 0x74, 0x03, 0x93, 0x8f, 0x8a, 0xad, 0xa9, 0x19, 0xc5, 0x08, 0x7c, 0x5d, 0x76,
	0x96, 0x40, 0xf9, 0xba, 0x14, 0x53, 0x08, 0x9d, 0xb9, 0x62, 0xfd, 0x7a, 0xdc, 0x8f, 0xd5, 0x01,
	0xc2, 0x63, 0x5b, 0x23, 0xb6, 0x10, 0x0d, 0x0a, 0x31, 0x97, 0x43, 0xa4, 0xfc, 0x2a, 0x4c, 0x92,
	0x5f, 0xa8, 0xff, 0x71, 0x17, 0x9e, 0x02, 0xb2, 0xc5, 0xf9, 0xaf, 0x3b, 0x74, 0xfd, 0x0c, 0x00,
	0x00, 0xff, 0xff, 0x30, 0xf8, 0x50, 0xdf, 0x03, 0x01, 0x00, 0x00,
}
