apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ms-users-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-users-app
  template:
    metadata:
      labels:
        app: ms-users-app
    spec:
      containers:
        - name: ms-users-app
          image: ms-users:latest
          ports:
          - containerPort: 3001
            protocol: TCP