apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-users-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-users-app
  template:
    metadata:
      labels:
        app: ms-users-app
    spec:
      containers:
        - name: ms-users-app
          image: ostapetc/ms-users:latest
          imagePullPolicy: Always
          command: [ "./main" ]
          ports:
            - containerPort: 3001
              protocol: TCP
          env:
            - name: "POD_IP"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "IDG_SERVER_ADDR"
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: IDG_SERVER_ADDR
