apiVersion: v1
kind: Service
metadata:
  name: ms-users-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: ms-users-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002