apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ms-idg-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-idg-app
  template:
    metadata:
      labels:
        app: ms-idg-app
    spec:
      containers:
        - name: ms-idg-app
          image: ms-idg:latest
          ports:
          - containerPort: 3002
            protocol: TCP
